module.exports.constants = {

 
    user: {
        //Registration and Login
        "USERNAME_REQUIRED": "Email is required",
        "FIRSTNAME_REQUIRED": "Firstname is required",
        "LASTNAME_REQUIRED": "Lastname is required",
        "PHONE_REQUIRED": "Phone number is required",
        "EMAIL_REQUIRED": "Email is required",
        "ROLE_REQUIRED": "Role is required",
        "EMAIL_EXIST": "Email-Id already exists.",
        "NUMBER_EXIST": "Mobile number is already exists.",
        "WRONG_EMAIL": "Email-Id does not exists",
        "PASSWORD_REQUIRED": "Password is required",
        "PAYLOAD_REQUIRED": "Payload is required",
        "UNVERIFIED": "You have not verified your account. Please verify",
        "USERNAME_NOT_APPROVED": "You have not approved by the admin",
        "SUCCESSFULLY_REGISTERED": "Successfully registered",
        "SUCCESSFULLY_LOGGEDIN": "Successfully logged in",
        "WRONG_USERNAME": "Username does not exists",
        "WRONG_PASSWORD": "Password is wrong!",
        "CURRENT_PASSWORD": "Current Password is wrong!",
        "INVALID_USER": "Invalid User. Your email does not exist to our system.",
        "ALREADY_VERIFIED": "You have already verified your email. Please login to website.",
        "ERROR_MAIL": "There is some error to send mail to your email id.",
        "LINK_MAIL": "Link for reset password has been sent to your email id.",
        "PASSWORD_CHANGED": "Password has been changed",
        "USERNAME_ALREADY": "Username is already exits.",
        "USERNAME_INACTIVE": "User is inactive",
        "CONPASSWORD_REQUIRED": "Confirm Password is required",
        "CURRENTPASSWORD_REQUIRED": "Current Password is required",
        "CONFIRM_PASSWORD_NOTMATCH": "Confirm Password is not Match",
        "ID_REQUIRED": "id Is Required",
        "UPDATED_USER": "User updated successfully.",
        "USERNAME_VERIFIED": "User is not verified.",
        "INVALID_CRED" : "Invalid login credentials.",
        "COMPANY_REQUIRED": " Company id required.",
        "DOMAIN_REQUIRED": "Domain key required.",
        "CONTACT_ADMIN":"Unable to login. Please contact admin.",
        "INVALID_IP" : "Ip address is not in whitelist.",
        "INVALID_LOCATION":"Unable to login .Please login at company\'s location.",
        "INVALID_IMAGE":"Invalid video type.",
        "VERIFICATION_SENT" : "Verfication email has sent, Please crosscheck your email.",
        "NOT_EXIST":"User not exist.",
        "DELETED" : "User deleted successfully.",
        "SUCCESSFULLY_SENT":"Email sent successfully.",
        "SUCCESSFULLY_INVITED":"User successfully invited"
    },
    CATEGORY: {
        NAME_REQUIRED: 'Name is required',
        ID_REQUIRED: 'Id is required',
        NAME_EXIST: 'Category with same name already exists',
        UPDATED: 'Category updated successfully',
        ADDED: 'Category added successfully',
        INVALID_ID: 'Invalid id',
        ALREADY_IN_USE: 'Category is already in use',
        DELETED: 'Category deleted successfully',
      },
      group: {
        NAME_REQUIRED: 'Name is required',
        ID_REQUIRED: 'Id is required',
        NAME_EXIST: 'Group with same name already exists',
        UPDATED: 'Group updated successfully',
        ADDED: 'Group added successfully',
        INVALID_ID: 'Invalid id',
        ALREADY_IN_USE: 'Group is already in use',
        DELETED: 'Group deleted successfully',
      },
      invitaion:{
        "USERNAME_REQUIRED": "Email is required",
        "FIRSTNAME_REQUIRED": "Firstname is required",
        "LASTNAME_REQUIRED": "Lastname is required",
        "PHONE_REQUIRED": "Phone number is required",
        "EMAIL_REQUIRED": "Email is required",
        "ROLE_REQUIRED": "Role is required",
        "NOT_INVITED":"This user is not invited",
        "ALREDY_INVITED":"This user is already invited",
        "ALREDYINVITED":"These users is already invited",
        "USER_REGISTER":"This user is alredy register",
        "Invited": 'Invited successfully',
      },
      PRODUCT:{
        "NAME_REQUIRED": "Product name is required",
        "PRICE_REQUIRED": "Price is required",
        "ADDED": 'Product added successfully',
        "DELETED":'Product deleted successfully',
        "PHONE_REQUIRED": "Phone number is required",
        "EMAIL_REQUIRED": "Email is required",
        "ROLE_REQUIRED": "Role is required",
        "NOT_INVITED":"This user is not invited",
        "ALREDY_INVITED":"This user is alredy invited",
        "USER_REGISTER":"This user is alredy register"
      },

      CARD:{
        "CARD_ADDED":"Card added successfully",
        "CARD_EXIST":"Card is already exist",
        "CARD_DELETED":"Card is deleted successfully"
      },
      subscriptionplan: {
        PLAN_ADD: 'Subscription plan added successfully.',
        INVALID_CARD: 'This card is not valid',
        ID_REQUIRED: 'Id Required.',
        GET_PLAN_DATA: 'SubscriptionPlan fetch successfully.',
        INVALID_ID: 'Invalid Id.',
        PLAN_UPDATED: 'Subscription plan updated successfully.',
        ALL_PLAN_DATA: 'All SubscriptionPlan fetch successfully.',
        DELETE_PLAN: 'SubscriptionPlan deleted successfully.',

      },
      SUBSCRIPTION_PLAN: {
        NAME_REQUIRED: "Name is required",
        NAME_EXIST: "Same name already exists",
        AMOUNT_REQUIRED: "Amount is required",
        UNABLE_TO_CREATE_PRODUCT: "Unable to create product",
        UNABLE_TO_CREATE_PLAN: "Unable to create plan",
        ADDED: "Subscription plan added successfully",
        UPDATED: "Subscription plan updated successfully",
        INVALID_ID: "Invalid id",
        FETCHED: "Subscription plan fetched successfully",
        ID_REQUIRED: "Id is required",
        DELETED: "Subscription plan removed successfully",
        INVALID_USER: "Invalid user",
        BUY_SUBSCRIPTION: "Subscription plan purchased successfully",
        PAYMENT_FAILED: "Payment failed",
        SUBSCRIPTION_CANCELLED: "Subscription cancelled successfully",
        SUBSCRIPTION_NOT_FOUND: "Subscription not found",
        INVALID_CARD: "Invalid card",
        USER_ID_REQUIRED: "User_id is required",
        ACTIVE_SUBSCRIPTION_FETCHED: "Active subscription fetched successfully",
        NO_SUBSCRIPTION_FOUND: "No subscription found",
        INVALID_USER_ID: "Invalid user id",
        INVALID_SUBSCRIPTION_PLAN_ID: "Invalid subscription plan id",
    },
}
